mybatis:
  type-aliases-package: com.lostsheep.technology.learning.mybatis.domain
  mapper-locations: mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
logging:
  level: 
    root: warn
    com.lostsheep.technology.learning.mybatis: debug
spring:
  datasource:
    url: jdbc:mysql://47.112.208.165:3306/lostsheep?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # druid 数据库连接池配置
    druid:
      # 初始化连接池连接数
      initial-size: 3
      # 连接池最小活跃数
      min-idle: 3
      # 连接池最大连接数
      max-active: 15
      # 获取连接等待超时时间
      max-wait: 5000
      # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-connect-error-millis: 90000
      # 一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 1800000
      # 获取时检测
      test-on-borrow: false
      # 归还时检测
      test-on-return: false
      # 空闲检测
      test-while-idle: true
