server:
  port: 8080


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location:
      max-file-size: 512MB
      max-request-size: 1024MB
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    com.lostsheep.technology.learning.async.upload: debug
