server:
  port: 8080

zk.port:


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      location:
      max-file-size: 512MB
      max-request-size: 1024MB
  jackson:
    default-property-inclusion: non_null
logging:
  level:
    com.lostsheep.technology.learning.async.upload: debug

processor.namespace: com.lostsheep.technology.learning.async.upload.processor.DyProcessor,\
  com.lostsheep.technology.learning.async.upload.processor.TaobaoProcessor,\
  com.lostsheep.technology.learning.async.upload.processor.JDProcessor

pipeline.namespace: com.lostsheep.technology.learning.async.upload.pipe.HBasePipeline